/**
 * เนื้อหาฉบับร่างของ Terms of Service / Privacy Policy / AI Disclaimer (TH + EN)
 *
 * ที่มา: docs/internal/phase3-plan.md หัวข้อ B3 — คัดลอกตามต้นฉบับ ไม่ได้ปรับถ้อยคำทางกฎหมาย
 * ⚠️ ยังไม่ผ่านทนายความ — ตัวยึดในวงเล็บเหลี่ยม [ ... ] คือข้อที่รอคำตอบจริง
 *    (นโยบายคืนเงิน, เพดานความรับผิด, กฎหมายที่ใช้บังคับ, ผู้ให้บริการ AI ที่ใช้จริง,
 *    ระยะเวลาเก็บข้อมูล, มาตรฐานการเข้ารหัส, อายุขั้นต่ำ, ผู้ติดต่อ/DPO)
 *    หน้าเว็บต้องแสดงให้เห็นตามจริง ห้ามเติมค่าเดาแทน
 *
 * ไวยากรณ์ในเนื้อหา: **ตัวหนา** และ [ตัวยึด] — ตัวแสดงผลจัดการทั้งสองแบบ (ดู LegalDocument.vue)
 */

export type LegalLanguage = 'th' | 'en';
export type LegalDocKey = 'terms' | 'privacy';

export interface LegalSection {
  /** ใส่ id เมื่อมีลิงก์ลึกมาที่หัวข้อนี้ */
  id?: string;
  heading: string;
  body: string;
}

export interface LegalDocumentContent {
  title: string;
  /** "อัปเดตล่าสุด: [วันที่] · ฉบับร่าง v0.1" */
  updated: string;
  intro?: string;
  /** บรรทัดคำเตือนเฉพาะเอกสาร ต่อท้าย "DRAFT — pending legal review" */
  draftNotice: string;
  sections: LegalSection[];
}

/** คำปฏิเสธ AI ฉบับเต็ม (ใช้เป็นหัวข้อท้ายหน้า Terms) */
export const AI_DISCLAIMER_FULL: Record<LegalLanguage, { heading: string; lead: string; rest: string }> = {
  en: {
    heading: 'AI Disclaimer',
    lead: 'Not financial advice.',
    rest: 'This content is generated by AI based on the data provided and may be incomplete or inaccurate. It is for informational purposes only and is not a recommendation to buy, sell, or hold any asset. Always do your own research and consult a licensed financial advisor before making investment decisions.',
  },
  th: {
    heading: 'คำปฏิเสธความรับผิดชอบเกี่ยวกับ AI',
    lead: 'ไม่ใช่คำแนะนำทางการเงิน',
    rest: 'เนื้อหานี้สร้างโดย AI จากข้อมูลที่ได้รับ อาจไม่ครบถ้วนหรือไม่ถูกต้อง มีไว้เพื่อการให้ข้อมูลเท่านั้น ไม่ใช่คำแนะนำให้ซื้อ ขาย หรือถือครองสินทรัพย์ใดๆ โปรดศึกษาข้อมูลด้วยตนเองและปรึกษาที่ปรึกษาทางการเงินที่ได้รับอนุญาตก่อนตัดสินใจลงทุน',
  },
};

const TERMS_EN: LegalDocumentContent = {
  title: 'Terms of Service — Wisenancial',
  updated: 'Last updated: [DATE] · Draft v0.1',
  draftNotice: 'Not legal advice. Requires review by a qualified lawyer before publication or use.',
  sections: [
    {
      heading: '1. Acceptance of Terms.',
      body: 'By creating an account or using Wisenancial ("the Service"), you agree to these Terms. If you do not agree, do not use the Service.',
    },
    {
      heading: '2. What the Service Is.',
      body: 'Wisenancial is a trading and investment journal and analytics tool. It helps you record trades, track portfolio performance, and access market data, news, and AI-generated summaries. **The Service is not a broker, is not a financial advisor, and does not execute trades on your behalf.**',
    },
    {
      heading: '3. No Investment Advice.',
      body: 'Nothing in the Service — including AI-generated summaries, risk analyses, "AI Picks," coaching content, or any other feature — constitutes financial, investment, tax, or legal advice. All content is for informational and educational purposes only. You are solely responsible for your own investment decisions. See the AI Disclaimer below, which applies throughout the Service.',
    },
    {
      heading: '4. Accounts.',
      body: 'You must provide accurate information when registering and are responsible for keeping your login credentials secure. You must be of legal age in your jurisdiction to use the Service.',
    },
    {
      heading: '5. Subscriptions and Payments.',
      body: 'Paid features are billed via our payment processor (Stripe). Fees, billing cycles, and refund terms are as displayed at the time of purchase. [Placeholder — refund policy to be confirmed with the user before publishing.]',
    },
    {
      heading: '6. Broker Connections.',
      body: 'If you connect a third-party broker account, you authorize the Service to read your trading data for the purpose of importing it into your journal. Credentials are stored encrypted. You may disconnect at any time from account settings.',
    },
    {
      heading: '7. User Content.',
      body: 'Content you post (journal entries, community posts, comments) remains yours. By posting in community areas, you grant the Service a license to display that content to other users as part of normal operation.',
    },
    {
      heading: '8. Acceptable Use.',
      body: "You agree not to misuse the Service, attempt to access other users' data, reverse-engineer the Service, or use it for any unlawful purpose.",
    },
    {
      heading: '9. Disclaimers and Limitation of Liability.',
      body: 'The Service is provided "as is." Market data may be delayed or inaccurate. AI-generated content may be incorrect. To the maximum extent permitted by law, Wisenancial is not liable for trading losses, investment decisions, or damages arising from use of the Service. [Placeholder — liability cap and jurisdiction-specific carve-outs need legal input.]',
    },
    {
      heading: '10. Termination.',
      body: 'You may delete your account at any time [see Privacy Policy for what happens to your data]. We may suspend or terminate accounts that violate these Terms.',
    },
    {
      heading: '11. Changes to These Terms.',
      body: 'We may update these Terms; continued use after an update constitutes acceptance.',
    },
    {
      heading: '12. Governing Law.',
      body: '[Placeholder — to be specified; likely Thailand given the target market, but this must be a deliberate legal decision, not a default.]',
    },
    {
      heading: '13. Contact.',
      body: '[Placeholder — support/legal contact email.]',
    },
    {
      id: 'ai-disclaimer',
      heading: AI_DISCLAIMER_FULL.en.heading,
      body: `**${AI_DISCLAIMER_FULL.en.lead}** ${AI_DISCLAIMER_FULL.en.rest}`,
    },
  ],
};

const TERMS_TH: LegalDocumentContent = {
  title: 'ข้อกำหนดการให้บริการ — Wisenancial',
  updated: 'อัปเดตล่าสุด: [วันที่] · ฉบับร่าง v0.1',
  draftNotice: 'ไม่ใช่คำแนะนำทางกฎหมาย ต้องได้รับการตรวจสอบจากทนายความที่มีคุณสมบัติก่อนเผยแพร่หรือใช้งานจริง',
  sections: [
    {
      heading: '1. การยอมรับข้อกำหนด',
      body: 'การสร้างบัญชีหรือใช้งาน Wisenancial ("บริการ") ถือว่าท่านยอมรับข้อกำหนดนี้ หากไม่ยอมรับ กรุณางดใช้บริการ',
    },
    {
      heading: '2. บริการนี้คืออะไร',
      body: 'Wisenancial เป็นเครื่องมือบันทึกการเทรด ติดตามพอร์ตการลงทุน และวิเคราะห์ข้อมูล ช่วยให้ท่านบันทึกรายการเทรด ติดตามผลตอบแทนของพอร์ต และเข้าถึงข้อมูลตลาด ข่าวสาร และสรุปที่สร้างโดย AI **บริการนี้ไม่ใช่โบรกเกอร์ ไม่ใช่ที่ปรึกษาทางการเงิน และไม่ดำเนินการซื้อขายแทนท่าน**',
    },
    {
      heading: '3. ไม่ใช่คำแนะนำการลงทุน',
      body: 'เนื้อหาทุกส่วนในบริการ — รวมถึงสรุปที่สร้างโดย AI, การวิเคราะห์ความเสี่ยง, "AI Picks", เนื้อหาจากโค้ช หรือฟีเจอร์อื่นใด — ไม่ถือเป็นคำแนะนำทางการเงิน การลงทุน ภาษี หรือกฎหมาย เนื้อหาทั้งหมดมีไว้เพื่อการให้ข้อมูลและการศึกษาเท่านั้น ท่านเป็นผู้รับผิดชอบแต่เพียงผู้เดียวต่อการตัดสินใจลงทุนของท่าน โปรดดูคำปฏิเสธความรับผิดชอบเกี่ยวกับ AI ด้านล่าง ซึ่งมีผลบังคับใช้ตลอดทั้งบริการ',
    },
    {
      heading: '4. บัญชีผู้ใช้',
      body: 'ท่านต้องให้ข้อมูลที่ถูกต้องเมื่อสมัครสมาชิก และรับผิดชอบในการรักษาความปลอดภัยของข้อมูลเข้าสู่ระบบ ท่านต้องมีอายุตามที่กฎหมายกำหนดในเขตอำนาจศาลของท่านจึงจะใช้บริการได้',
    },
    {
      heading: '5. การสมัครสมาชิกแบบเสียเงินและการชำระเงิน',
      body: 'ฟีเจอร์แบบเสียเงินเรียกเก็บผ่านผู้ให้บริการชำระเงิน (Stripe) ค่าธรรมเนียม รอบการเรียกเก็บ และเงื่อนไขการคืนเงินเป็นไปตามที่แสดง ณ เวลาที่ซื้อ [ตัวยึด — นโยบายการคืนเงินต้องยืนยันกับผู้ใช้ก่อนเผยแพร่จริง]',
    },
    {
      heading: '6. การเชื่อมต่อโบรกเกอร์',
      body: 'หากท่านเชื่อมต่อบัญชีโบรกเกอร์ภายนอก ท่านอนุญาตให้บริการอ่านข้อมูลการเทรดของท่านเพื่อนำเข้าสู่สมุดบันทึกของท่าน ข้อมูลรับรองตัวตนจะถูกเข้ารหัสก่อนจัดเก็บ ท่านสามารถยกเลิกการเชื่อมต่อได้ทุกเมื่อจากหน้าตั้งค่าบัญชี',
    },
    {
      heading: '7. เนื้อหาของผู้ใช้',
      body: 'เนื้อหาที่ท่านโพสต์ (บันทึกการเทรด โพสต์ในชุมชน ความคิดเห็น) ยังคงเป็นของท่าน การโพสต์ในพื้นที่ชุมชนถือว่าท่านอนุญาตให้บริการแสดงเนื้อหานั้นแก่ผู้ใช้อื่นตามการทำงานปกติของระบบ',
    },
    {
      heading: '8. การใช้งานที่เหมาะสม',
      body: 'ท่านตกลงจะไม่ใช้บริการในทางที่ผิด ไม่พยายามเข้าถึงข้อมูลของผู้ใช้อื่น ไม่ทำวิศวกรรมย้อนกลับกับบริการ และไม่ใช้เพื่อวัตถุประสงค์ที่ผิดกฎหมาย',
    },
    {
      heading: '9. ข้อจำกัดความรับผิดชอบ',
      body: 'บริการนี้ให้บริการ "ตามสภาพที่เป็นอยู่" ข้อมูลตลาดอาจล่าช้าหรือไม่ถูกต้อง เนื้อหาที่สร้างโดย AI อาจผิดพลาด Wisenancial ไม่รับผิดชอบต่อความสูญเสียจากการเทรด การตัดสินใจลงทุน หรือความเสียหายที่เกิดจากการใช้บริการ เท่าที่กฎหมายอนุญาต [ตัวยึด — เพดานความรับผิดและข้อยกเว้นตามเขตอำนาจศาลต้องผ่านการตรวจสอบทางกฎหมาย]',
    },
    {
      heading: '10. การยุติการใช้บริการ',
      body: 'ท่านสามารถลบบัญชีได้ทุกเมื่อ [ดูนโยบายความเป็นส่วนตัวสำหรับรายละเอียดว่าข้อมูลของท่านจะเป็นอย่างไร] เราอาจระงับหรือยุติบัญชีที่ละเมิดข้อกำหนดนี้',
    },
    {
      heading: '11. การเปลี่ยนแปลงข้อกำหนด',
      body: 'เราอาจปรับปรุงข้อกำหนดนี้ การใช้บริการต่อหลังการปรับปรุงถือเป็นการยอมรับ',
    },
    {
      heading: '12. กฎหมายที่ใช้บังคับ',
      body: '[ตัวยึด — ต้องระบุ คาดว่าจะเป็นประเทศไทยตามกลุ่มเป้าหมาย แต่ต้องเป็นการตัดสินใจทางกฎหมายที่ชัดเจน ไม่ใช่ค่าเริ่มต้น]',
    },
    {
      heading: '13. ติดต่อ',
      body: '[ตัวยึด — อีเมลฝ่ายสนับสนุน/กฎหมาย]',
    },
    {
      id: 'ai-disclaimer',
      heading: AI_DISCLAIMER_FULL.th.heading,
      body: `**${AI_DISCLAIMER_FULL.th.lead}** ${AI_DISCLAIMER_FULL.th.rest}`,
    },
  ],
};

const PRIVACY_EN: LegalDocumentContent = {
  title: 'Privacy Policy — Wisenancial',
  updated: 'Last updated: [DATE] · Draft v0.1',
  draftNotice:
    'Not legal advice. Requires review by a qualified lawyer (PDPA-specialized) before publication or use.',
  intro:
    "This policy explains how Wisenancial collects, uses, and protects your personal data, in line with Thailand's Personal Data Protection Act (PDPA).",
  sections: [
    {
      heading: '1. Data We Collect.',
      body: "Account data (name, username, email, hashed password); trading/investment data you enter (trades, portfolios, dividends); broker connection data (encrypted credentials, imported trade history) if you choose to connect a broker; usage data (AI feature usage, community posts/comments); payment data (handled by Stripe — we do not store your card details); technical data (IP address, device/browser info, for security and session management).",
    },
    {
      heading: '2. Why We Collect It (Legal Basis).',
      body: "To provide the Service you've signed up for (contract performance); to secure your account (legitimate interest); to process payments (contract performance); with your consent, for optional features (e.g. AI analysis of your portfolio, marketing communications if introduced later).",
    },
    {
      heading: '3. AI Features.',
      body: "Some features send your trade/portfolio data to third-party AI providers (currently Groq, Google Gemini, OpenAI, and Anthropic, used as configured) to generate summaries and analysis. [Placeholder — this needs the user's confirmation of exactly which providers are live in production before this section is finalized, since that determines which providers' own data-handling terms apply to your data.] We do not knowingly send this data for the providers' own model training beyond what each provider's own API terms specify.",
    },
    {
      heading: '4. Data Sharing.',
      body: 'We share data with: Stripe (payments), the AI providers listed above (for AI features you use), our hosting/database provider (Neon, PostgreSQL hosting), and no one else, except as required by law.',
    },
    {
      heading: '5. Data Retention.',
      body: '[Placeholder — depends on the account-deletion design decided in B1. Financial/billing records may need to be retained longer than account data for legal/tax reasons even after account deletion — this needs a specific retention schedule, not a blanket policy.]',
    },
    {
      heading: '6. Your Rights Under PDPA.',
      body: 'You have the right to: access your data (see "Export my data" in Settings, once built); rectify inaccurate data (edit profile); erase your data (delete account — subject to the retention exceptions noted above); withdraw consent for optional processing at any time; data portability (the JSON export); object to certain processing; lodge a complaint with Thailand\'s Personal Data Protection Committee (PDPC) if you believe your rights have been violated.',
    },
    {
      heading: '7. Data Security.',
      body: 'Passwords are hashed (never stored in plain text). Broker credentials are encrypted at rest. [Placeholder — this section should name the actual encryption standards used, confirmed against the real implementation, before publishing — do not publish unverified security claims.]',
    },
    {
      heading: '8. Children.',
      body: 'The Service is not directed at children under [age — placeholder, depends on jurisdiction-specific age of consent for data processing].',
    },
    {
      heading: '9. Changes to This Policy.',
      body: 'We will notify users of material changes.',
    },
    {
      heading: '10. Contact / Data Protection Officer.',
      body: '[Placeholder — PDPA generally expects a designated contact point for data subject requests; who this is needs to be decided by the user, not assumed.]',
    },
  ],
};

const PRIVACY_TH: LegalDocumentContent = {
  title: 'นโยบายความเป็นส่วนตัว — Wisenancial',
  updated: 'อัปเดตล่าสุด: [วันที่] · ฉบับร่าง v0.1',
  draftNotice:
    'ไม่ใช่คำแนะนำทางกฎหมาย ต้องได้รับการตรวจสอบจากทนายความที่เชี่ยวชาญ PDPA ก่อนเผยแพร่หรือใช้งานจริง',
  intro:
    'นโยบายนี้อธิบายวิธีที่ Wisenancial เก็บรวบรวม ใช้ และคุ้มครองข้อมูลส่วนบุคคลของท่าน ตามพระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 (PDPA)',
  sections: [
    {
      heading: '1. ข้อมูลที่เราเก็บรวบรวม',
      body: 'ข้อมูลบัญชี (ชื่อ ชื่อผู้ใช้ อีเมล รหัสผ่านที่เข้ารหัส) ข้อมูลการเทรด/การลงทุนที่ท่านกรอกเอง (รายการเทรด พอร์ตการลงทุน เงินปันผล) ข้อมูลการเชื่อมต่อโบรกเกอร์ (ข้อมูลรับรองตัวตนที่เข้ารหัส ประวัติการเทรดที่นำเข้า) หากท่านเลือกเชื่อมต่อโบรกเกอร์ ข้อมูลการใช้งาน (การใช้ฟีเจอร์ AI โพสต์/ความคิดเห็นในชุมชน) ข้อมูลการชำระเงิน (จัดการโดย Stripe — เราไม่จัดเก็บข้อมูลบัตรของท่าน) ข้อมูลทางเทคนิค (IP address ข้อมูลอุปกรณ์/เบราว์เซอร์ เพื่อความปลอดภัยและการจัดการเซสชัน)',
    },
    {
      heading: '2. เหตุผลในการเก็บรวบรวม (ฐานทางกฎหมาย)',
      body: 'เพื่อให้บริการตามที่ท่านสมัครใช้ (การปฏิบัติตามสัญญา) เพื่อรักษาความปลอดภัยบัญชีของท่าน (ประโยชน์โดยชอบด้วยกฎหมาย) เพื่อประมวลผลการชำระเงิน (การปฏิบัติตามสัญญา) และด้วยความยินยอมของท่านสำหรับฟีเจอร์ที่เป็นทางเลือก (เช่น การวิเคราะห์พอร์ตด้วย AI หรือการสื่อสารทางการตลาดหากมีในอนาคต)',
    },
    {
      heading: '3. ฟีเจอร์ AI',
      body: 'บางฟีเจอร์ส่งข้อมูลการเทรด/พอร์ตของท่านไปยังผู้ให้บริการ AI ภายนอก (ปัจจุบันคือ Groq, Google Gemini, OpenAI และ Anthropic ตามที่ตั้งค่าไว้) เพื่อสร้างสรุปและบทวิเคราะห์ [ตัวยึด — ส่วนนี้ต้องได้รับการยืนยันจากผู้ใช้ว่าผู้ให้บริการรายใดใช้งานจริงใน production ก่อนสรุปเนื้อหาสุดท้าย เนื่องจากจะกำหนดว่าข้อกำหนดการจัดการข้อมูลของผู้ให้บริการรายใดมีผลกับข้อมูลของท่าน] เราจะไม่ส่งข้อมูลนี้ไปใช้ฝึกโมเดลของผู้ให้บริการนอกเหนือจากที่ระบุไว้ในข้อกำหนดการใช้ API ของผู้ให้บริการแต่ละราย',
    },
    {
      heading: '4. การเปิดเผยข้อมูล',
      body: 'เราเปิดเผยข้อมูลแก่: Stripe (การชำระเงิน) ผู้ให้บริการ AI ที่ระบุข้างต้น (สำหรับฟีเจอร์ AI ที่ท่านใช้) ผู้ให้บริการโฮสติ้ง/ฐานข้อมูลของเรา (Neon, PostgreSQL) และไม่มีบุคคลอื่นใดอีก เว้นแต่กฎหมายกำหนด',
    },
    {
      heading: '5. ระยะเวลาการเก็บรักษาข้อมูล',
      body: '[ตัวยึด — ขึ้นอยู่กับการออกแบบการลบบัญชีที่ตัดสินใจใน B1 บันทึกทางการเงิน/การเรียกเก็บเงินอาจต้องเก็บรักษานานกว่าข้อมูลบัญชีด้วยเหตุผลทางกฎหมาย/ภาษี แม้หลังลบบัญชีแล้ว ต้องมีตารางระยะเวลาที่ชัดเจน ไม่ใช่นโยบายเหมารวม]',
    },
    {
      heading: '6. สิทธิของท่านตาม PDPA',
      body: 'ท่านมีสิทธิ: เข้าถึงข้อมูลของท่าน (ดู "ส่งออกข้อมูลของฉัน" ในหน้าตั้งค่า เมื่อสร้างเสร็จ) แก้ไขข้อมูลที่ไม่ถูกต้อง (แก้ไขโปรไฟล์) ลบข้อมูล (ลบบัญชี — อยู่ภายใต้ข้อยกเว้นเรื่องการเก็บรักษาข้างต้น) ถอนความยินยอมสำหรับการประมวลผลที่เป็นทางเลือกได้ทุกเมื่อ การโอนย้ายข้อมูล (การส่งออกไฟล์ JSON) คัดค้านการประมวลผลบางประเภท และร้องเรียนต่อคณะกรรมการคุ้มครองข้อมูลส่วนบุคคล (สคส./PDPC) หากท่านเชื่อว่าสิทธิของท่านถูกละเมิด',
    },
    {
      heading: '7. ความปลอดภัยของข้อมูล',
      body: 'รหัสผ่านถูกเข้ารหัสแบบ hash (ไม่เก็บเป็นข้อความธรรมดา) ข้อมูลรับรองตัวตนของโบรกเกอร์ถูกเข้ารหัสขณะจัดเก็บ [ตัวยึด — ส่วนนี้ควรระบุมาตรฐานการเข้ารหัสจริงที่ใช้ ยืนยันกับการทำงานจริงของระบบก่อนเผยแพร่ — ห้ามเผยแพร่คำกล่าวอ้างด้านความปลอดภัยที่ยังไม่ได้ตรวจสอบ]',
    },
    {
      heading: '8. เด็ก',
      body: 'บริการนี้ไม่ได้มุ่งเป้าไปยังเด็กอายุต่ำกว่า [อายุ — ตัวยึด ขึ้นอยู่กับอายุความยินยอมด้านการประมวลผลข้อมูลตามกฎหมายแต่ละเขตอำนาจ]',
    },
    {
      heading: '9. การเปลี่ยนแปลงนโยบาย',
      body: 'เราจะแจ้งผู้ใช้เมื่อมีการเปลี่ยนแปลงที่มีนัยสำคัญ',
    },
    {
      heading: '10. ติดต่อ / เจ้าหน้าที่คุ้มครองข้อมูลส่วนบุคคล',
      body: '[ตัวยึด — โดยทั่วไป PDPA คาดหวังให้มีช่องทางติดต่อที่ชัดเจนสำหรับคำร้องของเจ้าของข้อมูล ต้องให้ผู้ใช้เป็นผู้ตัดสินใจว่าใครทำหน้าที่นี้ ไม่ใช่การสมมติเอาเอง]',
    },
  ],
};

export const LEGAL_DOCUMENTS: Record<LegalDocKey, Record<LegalLanguage, LegalDocumentContent>> = {
  terms: { en: TERMS_EN, th: TERMS_TH },
  privacy: { en: PRIVACY_EN, th: PRIVACY_TH },
};

/** แบนเนอร์ที่ต้องเห็นบนทุกหน้ากฎหมาย */
export const LEGAL_DRAFT_BANNER: Record<LegalLanguage, string> = {
  en: 'DRAFT — pending legal review',
  th: 'ฉบับร่าง — รอการตรวจสอบทางกฎหมาย',
};
